---
- name: echo
  shell: echo 'Ansible vagrant mariadb'
- name: Install Mariadb dependencies
  apt: name={{item}} update_cache=yes
  with_items:
    - mariadb-client
    - mariadb-server
    - python-mysqldb
  become: yes
- name: Configuration file
  template:
    src: "{{ item }}"
    dest: "/etc/mysql/mariadb.conf.d/{{ item }}"
  with_items:
    - 50-server.conf
    - 50-server.cnf
  become: yes

- name: Ensure the Mariadb service is running
  service: name=mariadb state=started enabled=yes

- name: Root user
  mysql_user:
    name: root
    password: "{{ root_db_password }}"
    priv: '*.*:ALL'
    host: "%"
    state: present
  become: yes

- name: Create datababse
  mysql_db:
    name: "{{ user_db_name }}"
    state: present
  become: yes

- name: Create user
  mysql_user:
    name: "{{ user_name }}"
    host: "%"
    password: "{{ user_password }}"
    priv: '{{ user_db_name }}.*:ALL'
    state: present
  become: yes
