---

- name: "Download repo"
  template:
    src: "centos-repo.tpl"
    dest: "/etc/yum.repos.d/MariaDB.repo"
  when: ansible_distribution == 'CentOS'

- name: Install Mariadb dependencies
  package:
    name: "{{item}}"
    state: present
  with_items:
    - mariadb-client
    - mariadb-server
    - python-mysqldb
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install Mariadb dependencies
  package:
    name: "{{item}}"
    state: present
  with_items:
    - MariaDB-server
    - MariaDB-client
    - MySQL-python
  when: ansible_distribution == 'CentOS'

- name: Configuration file
  template:
    src: "{{ item }}"
    dest: "/etc/mysql/mariadb.conf.d/{{ item }}"
  with_items:
    - 50-server.conf
    - 50-server.cnf
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

#- fail:
#    msg: "stop"

- name: Configuration file
  template:
    src: "my.cnf"
    dest: "/etc/my.cnf"
  when: ansible_distribution == 'CentOS'

- name: Ensure the Mariadb service is running
  service: name=mariadb state=started enabled=yes

- name: Root user
  mysql_user:
    name: root
    password: "{{ root_db_password }}"
    priv: '*.*:ALL'
    host: "%"
    state: present

- name: Create datababse
  mysql_db:
    name: "{{ user_db_name }}"
    state: present

- name: Create user
  mysql_user:
    name: "{{ user_name }}"
    host: "%"
    password: "{{ user_password }}"
    priv: '{{ user_db_name }}.*:ALL'
    state: present

- name: Restart service
  service:
    name: mariadb
    state: restarted