---

apiVersion: v1
kind: Secret
metadata:
  name: keycloak
  namespace: keycloak
  labels:
    app: keycloak
data:
  # echo -n "keycloak" | base64
  postgress-password: a2V5Y2xvYWs=
  #echo -n "admin" | base64
  admin-password: YWRtaW4=
