---

- hosts: all
  remote_user: vagrant
  roles:
    - ambari/ambari-common
  become: yes

- hosts: ambari-agent
  remote_user: vagrant
  roles:
    - ambari/ambari-agent
  become: yes

- hosts: ambari-master
  remote_user: vagrant
  roles:
    - ambari/ambari-master
  become: yes