# Default values for mariadb.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: postgres
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5432
  portName: postgres

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

volumeMounts:
  name: postgres
  claimName: postgres

volume:
  accessModes: ReadWriteOnce
  resourcesRequestsStorage: 20Gi

secret:
  data:
    # echo -n "user" | base64
    userpassword: dXNlcg==

env:
  POSTGRES_DB: user
  POSTGRES_USER: user
