kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: testing-edit
  namespace: testing # This binding only applies in the "testing" namespace
subjects:
  - kind: Group # May be "User", "Group" or "ServiceAccount"
    name: testing
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io