---

- hosts: all
  remote_user: root
  vars:
    partition_type: "standard"
    disk: "/dev/sda"
    partition_number: 1
  tasks:
    - debug:
        msg: "Ubuntu desktop provisioning"
  roles:
    - { role: "../../ansible/roles/common" }
    - { role: "../../ansible/roles/disk-utils" }
    - { role: "../../ansible/roles/docker" }
    - { role: "../../ansible/roles/developer " }
  become: yes