---

# Start container
- name: Create container(s)
  lxc_container:
    name: "{{ item.name }}"
    container_log: true
    container_log_level: INFO
    template: "{{ item.template }}"
    template_options: --release "{{ item.release}}" --arch=amd64
    container_config:
    - "lxc.start.auto = 1"
    - "lxc.network.ipv4 = {{ item.ip }}"
    - "lxc.network.ipv4.gateway = 10.0.3.1"
    state: started
  register: create_vm
  loop: "{{ containers }}"

- name: Run first commands
  lxc_container:
    name: "{{ item.name }}"
    container_command: |
      apt-get update
      apt-get install -y python
  loop: "{{ containers }}"
