---

- name: Install LXC dependencies
  package:
    name: "{{ item }}"
  with_items:
  - lxc
  - lxctl
  - python-lxc
  - libvirt-daemon
  - libvirt-clients

- name: Copy config files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
  #- { src: 'lxc-net', dest: '/etc/default/lxc-net' }
  - { src: 'default.conf', dest: '/etc/lxc/default.conf' }
