apiVersion: v1
kind: Secret
metadata:
  name: {{ template "postgres.fullname" . }}
  #namespace: postgres
data:
  rootpassword: {{ .Values.secret.data.rootpassword }}
  userpassword: {{ .Values.secret.data.userpassword }}
