apiVersion: v1
kind: Service
metadata:
  name: {{ template "postgres.fullname" . }}
  #namespace: mariadb
  labels:
    app: {{ template "postgres.name" . }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    app: {{ template "postgres.name" . }}
    tier: database
  clusterIP: None
