
---
- hosts: all
  remote_user: root
  roles:
    - test
    - common
    - docker
    - docker-config
  #- import_playbook: test.yml
  #- import_playbook: common.yml
  #- import_playbook: docker.yml
  #- import_playbook: docker-config.yml