apiVersion: v1
kind: Secret
metadata:
  name: {{ template "mariadb.fullname" . }}
  #namespace: mariadb
data:
  rootpassword: {{ .Values.secret.data.rootpassword }}
  userpassword: {{ .Values.secret.data.userpassword }}
