apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "mariadb.fullname" . }}
  #namespace: mariadb
  labels:
    app: {{ template "mariadb.name" . }}
spec:
  accessModes:
    - {{ .Values.volume.accessModes }}
  resources:
    requests:
      storage: {{ .Values.volume.resourcesRequestsStorage }}