---

- name: Add locale gen file
  template:
    src: locale.gen
    dest: /etc/locale.gen

- name: Update locales
  shell: |
    locale-gen
    dpkg-reconfigure locales -f noninteractive

- name: Install Common
  package:
    name: "{{ item }}"
  with_items:
    - vim
    - git
    - curl
    - wget
    - net-tools
    - xinetd
    - htop
    - psmisc
    - iputils-*
    - ssh
    - python
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common

