---

- include_tasks: centos.yml
  when: ansible_distribution == 'CentOS'

- include_tasks: freebsd.yml
  when: ansible_distribution == 'FreeBSD'

- include_tasks: ubuntu-debian.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

#- name: Add locale gen file
#  template:
#    src: locale.gen
#    dest: /etc/locale.gen
#
#- name: Update locales
#  shell: |
#    locale-gen
#    dpkg-reconfigure locales -f noninteractive

#- name: Wait for automatic system updates
#  become: true
#  shell: while sudo fuser /var/lib/dpkg/{{ item }} >/dev/null 2>&1; do sleep 1; done;
#  with_items:
#    - lock
#    - lock-frontend

- name: Install Common
  package:
    name: ['vim', 'git', 'curl', 'wget', 'net-tools', 'xinetd', 'htop', 'psmisc', 'iputils-*', 'python']
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu' or  ansible_distribution == 'CentOS'
