apiVersion: v1
kind: Secret
metadata:
  name: mariadb
  namespace: web-dynamic
  labels:
    app: web-dynamic
data:
  # echo -n "root" | base64
  rootpassword: cm9vdA==
  # echo -n "mariadb" | base64
  userpassword: bWFyaWFkYg==

