apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb
  namespace: web-dynamic
  labels:
    app: web-dynamic
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi