---

- hosts: all
  remote_user: root
  vars:
    partition_type: "growpart"
    disk: "/dev/sda"
    partition_number: 1
  tasks:
    - debug:
        msg: "Linux desktop provisioning"
  roles:
    - common
    - disk-utils
  become: yes