---

- debug:
    msg: "X11 Ubuntu"
  when: ansible_distribution == 'Ubuntu'

- name: Install Dependencies
  package:
    name: "{{ item }}"
  with_items:
    - lightdm # vi /usr/share/lightdm/lightdm.conf.d/50-xfce-greeter.conf
    - xfonts-base
    - xserver-xorg
    - xterm
    #- xorg
    - xfce4
  when: ansible_distribution == 'Ubuntu'

- debug:
    msg: "X11 Debian"
  when: ansible_distribution == 'Debian'

- name: Install Dependencies
  package:
    name: "{{ item }}"
  with_items:
    - xorg
    - xfce4
  when: ansible_distribution == 'Debian'