
---

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: registrylocalvolume
  namespace: registry
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: registrylocalvolume
  namespace: registry
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: registrylocalvolume
  local:
    path: /data/registry
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - node1

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: registrylocalvolume
  namespace: registry
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: registrylocalvolume