apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlabetc
  namespace: gitlab
  labels:
    app: gitlab
    folder: etc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlablog
  namespace: gitlab
  labels:
    app: gitlab
    folder: log
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlabopt
  namespace: gitlab
  labels:
    app: gitlab
    folder: opt
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
