---

- hosts: kubernetes-ubuntu
  remote_user: vagrant
  vars:
    partition_type: "parted"
    k8s_master_node: "kubernetes-ubuntu"
    k8s_apiserver_advertise_address: "192.168.33.16"
    k8s_apiserver_cert_extra_sans: "192.168.33.16"
    k8s_ingress_external_ips: [ "192.168.33.16" ]
    k8s_dashboard_port: 31223
    docker_insecure_registries: ["registry.192.168.33.16.nip.io"]
  roles:
    #- common
    #- disk-utils
    #- docker
    #- kubernetes
    #- kubernetes-config
    - kubernetes-istio
    - kubernetes-modules
    - kubernetes-rookio-ceph
  become: yes