kind: Service
apiVersion: v1
metadata:
  name: nginx-default-service
  namespace: default
  labels:
    app: nginx-default
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: nginx-default
  type: NodePort
  sessionAffinity: None