
---
- hosts: all
  remote_user: root
  vars:
    docker_version: 17.03.2~ce-0~debian-stretch
  roles:
    - test
    - common
    - docker
    - docker-config
    - kubernetes
    - kubernetes-config