---

- name: Register token
  shell: cat $HOME/.kube/token
  register: kube_token

- name: Register config
  shell : cat $HOME/.kube/config | sed -e 's/10.0.4.100:6443/192.168.33.15:6443/'
  register: kube_config

- name: "Copy token and config locally"
  copy:
    content: "{{ kube_token.stdout }}"
    dest: $HOME/.kube/token
  delegate_to: localhost
  become: false

- name: "Copy config and config locally"
  copy:
    content: "{{ kube_config.stdout }}"
    dest: $HOME/.kube/config
  delegate_to: localhost
  become: false

- name: "Dashboard token : "
  debug:
    msg: "{{ kube_token.stdout }}"