---

# make ssh work localhost

- name: "Copy ssh key"
  copy:
    src: private_key
    dest: /home/vagrant/.ssh/ir_rsa
    owner: vagrant
    group: vagrant
    mode: '0600'

- name: "Disable selinux"
  command: setenforce 0

# disable iptable
# systemctl stop firewalld
# systemctl disable firewalld
- name: "Disable FirewalldD"
  systemd:
    name: firewalld
    state: stopped
    enabled: no

# wget -O /etc/yum.repos.d/ambari.repo http://public-repo-1.hortonworks.com/ambari/centos6/2.x/updates/2.5.1.0/ambari.repo
# yum install ambari-server -y

# wget http://public-repo-1.hortonworks.com/HDP/centos7/3.x/updates/3.0.1.0/hdp.repo -O /etc/yum/hdp.repo
# http://public-repo-1.hortonworks.com/ambari/centos7/2.x/updates/2.7.1.0/ambari.repo -O /etc/yum.repos.d/ambari.repo

# yum-config-manager --add-repo http://public-repo-1.hortonworks.com/HDP/centos7/3.x/updates/3.0.1.0/hdp.repo
# yum-config-manager --add-repo http://public-repo-1.hortonworks.com/ambari/centos6/2.x/updates/2.5.1.0/ambari.repo

- name: "Download repo"
  get_url:
    url: http://public-repo-1.hortonworks.com/ambari/centos7/2.x/updates/2.7.3.0/ambari.repo
    dest: /etc/yum.repos.d/ambari.repo

- name: Install Ambari
  package:
    name: [
      'ntp',
      'ambari-server',
      #'ambari-agent',
      'mysql-connector-java*'
    ]
    state: present

- name: "Start NTPD"
  systemd:
    name: ntpd
    state: started
    enabled: yes

- name: "Ambari setup"
  shell: ambari-server setup -s > ambari-setup/log
# ambari-server setup -s

- name: "Ambari start"
  shell: ambari-server start
# ambari-server start
# ambari-server status

# http://192.168.33.17:8080/#/login
# admin / admin


- name: "install mysql driver for hive"
  shell: |
    cd /var/lib/ambari-server/resources/
    ln -s /usr/share/java/mysql-connector-java.jar /var/lib/ambari-server/resources/mysql-connector-java.jar

    ambari-server setup --jdbc-db=mysql --jdbc-driver=/usr/share/java/mysql-connector-java.jar
  args:
    creates: /var/lib/ambari-server/resources/mysql-connector-java.jar


### TODO

# FIX this
#  Value is less than the recommended default of 896
#  HBase Master Heap Size. In embedded mode, total heap size is
#  sum of master and regionserver heap sizes.

# Install das ui
# https://docs.hortonworks.com/HDPDocuments/DAS/DAS-1.2.0/installation/content/das_adding_the_das_service_through_the_ambari_ui.html