- hosts: all
  remote_user: root
  tasks:
  - name: echo
    shell: echo 'Install NGINX Service'
  - name: install Nginx
    apt:
      name: nginx
      update_cache: yes
    become: yes
  - name: Start service NGINX, if not running
    service:
      name: nginx
      state: started
    become: yes
