---

kind: Namespace
apiVersion: v1
metadata:
  name: postgres
  labels:
    name: postgres

---

apiVersion: v1
kind: Secret
metadata:
  name: postgres
  namespace: postgres
type: Opaque
stringData:
  password: master-password
  replicaPassword: replica-password

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres
  name: postgres
  namespace: postgres
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app: postgres

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres-replica
  name: postgres-replica
  namespace: postgres

spec:
  type: ClusterIP
  ports:
    - name: postgres-replica
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app: postgres-replica

