---

- name: "Resize LVM partion"
  shell: |
    growpart {{ disk }} {{ partition_number }}
    resize2fs {{ disk }}{{ partition_number }}
  when: partition_type == 'growpart'

- name: "Resize Standard partion"
  shell: |
    parted {{ disk }} resizepart {{ partition_number }} Y 100%
    resize2fs {{ disk }}{{ partition_number }}
  when: partition_type == 'parted'

