---

- debug:
    msg: "Resize partition"

- name: "Resize LVM partion"
  shell: |
    growpart {{ disk }} {{ partition_number }}
    resize2fs {{ disk }}{{ partition_number }}
  when: partition_type == 'lvm'

- name: "Resize Standard partion"
  shell: |
    sgdisk -e {{ disk }}
    parted {{ disk }} resizepart {{ partition_number }} Y 100%
    resize2fs {{ disk }}{{ partition_number }}
  when: partition_type == 'standard'

- name: "Resize ZFS partion"
  shell: |
    #gpart show {{ disk }}
    gpart recover {{ disk }}
    gpart resize -i 1 -s 512a 4k {{ disk }}
    gpart resize -i {{ partition_number }} -s 40G -a 4k {{ disk }}
    zpool online -e zroot {{ disk }}p{{ partition_number }}

  when: partition_type == 'zfs'


- shell:  df -H | grep {{ filesystem }}
  register: disk_space

- debug:
    msg: "{{ disk_space.stdout }}"

