---

- name: Add Docker GPG key
  apt_key:
    url: "{{ docker_pgp_key }}"
    validate_certs: false

- name: Add Docker APT repository
  apt_repository:
    repo: "{{ docker_repo }}"

- name: Install Docker
  package:
    name: "{{item}}"
  with_items:
    - docker-ce
    - docker-compose
  register: docker_installed

#- name: Add docker insecure registry
#  template:
#   src: daemon.json.j2
#    dest: /etc/docker/daemon.json

#- name: Open Docker socket
#  lineinfile:
#    path: /etc/default/docker
#    line: 'DOCKER_OPTS="-H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock"'
#    create: no
#  when: docker_open_socket

#- name: Restart docker
#  service:
#    name: docker
#    state: restarted
#  when: docker_installed is changed
