kind: Pod
apiVersion: v1
metadata:
  name: pod-using-nfs
spec:
  volumes:
    - name: nfs-volume
      nfs:
        server: 192.168.99.50
        path: /var/nfs

  containers:
    - name: app
      image: alpine

      volumeMounts:
        - name: nfs-volume
          mountPath: /mnt/nfs

      command: ["/bin/sh"]
      args: ["-c", "while true; do date; sleep 5; done"]