---
# defaults file for ansible-role-nginx

nginx_user: root
nginx_group: root
nginx_distribution: mainline # mainline or stable
nginx_package_name: nginx
nginx_custom: False
nginx_custom_path:  /tmp/nginx
# these debs need to be already on the server
nginx_custom_debs:
  - nginx_*
nginx_delete_default: True
nginx_worker_processes: auto
nginx_worker_connections: 1024
nginx_worker_rlimit_nofile: 8192
nginx_multi_accept: "on"
nginx_pid: "/var/run/nginx.pid"
nginx_error_log: "/var/log/nginx/error.log warn"
nginx_access_log: "/var/log/nginx/access.log main buffer=16k"
# nginx_access_log: "/var/log/nginx/access.log main"
nginx_mime_file_path: "/etc/nginx/conf.d/mime.types"
nginx_cloudflare_ips_conf: "/etc/nginx/conf.d/cloudflare-ips.conf"
nginx_keepalive_timeout: 75
nginx_keepalive_requests: 100000
nginx_sendfile: "on"
nginx_tcp_nopush: "on"
nginx_tcp_nodelay: "on"

nginx_client_body_buffer_size: 128k
nginx_client_max_body_size: 20m

nginx_types_hash_max_size: 2048
nginx_server_names_hash_bucket_size: 64

nginx_open_file_cache_enable: false
nginx_open_file_cache: "max=1000 inactive=20s"
nginx_open_file_cache_valid: 30s
nginx_open_file_cache_min_uses: 5
nginx_open_file_cache_errors: off

nginx_dhparam_path: False #"/etc/nginx/conf.d/ssl/dhparam.pem"
nginx_dhparam_encryption_size: 2048
