
---
- hosts: all
  remote_user: root
  tasks:
  - name: echo
    shell: echo 'Ansible vagrant docker'
  - name: Install Docker Common dependencies
    apt: name={{item}} update_cache=yes
    with_items:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    become: yes
  - name: Add Docker GPG key
    apt_key:
      url: https://download.docker.com/linux/debian/gpg
      validate_certs: false
    become: yes
  - name: Add Docker APT repository
    apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/debian stretch stable"
    become: yes
  - name: Install Docker
    apt: name={{item}} update_cache=yes
    with_items:
      - docker-ce
      - docker-compose
    become: yes
